### ISSUE TITLE
Feedback on the Perth Face to Face Meeting 18th of May 2018

### ISSUE THREAD

**Issue by rowlandm** [rse-aunz/rse-au#11]
Hi everyone,

I put together some notes in a google doc. You should all have comment ability, or stick them in the comments below.

https://docs.google.com/document/d/1-70pEUH_l_1osgZecoIWDJgl19rZVu_WfwXKF0ViIO4/edit#

**Comment by ericbastholm** [comment]
As for hashtags - RSE is pretty prevalent on twitter for Relationships and Sex Education and RSEng is used by the community instead. Unless there are better ways I might tag Astro SE as 
#RSEng #Astronomy

Perhaps #RSEng_AUNZ for aussie/kiwi chapter where distinction is required?

**Comment by rowlandm** [comment]
Thanks Eric! That has been pretty consistent message about RSE causing confusion.

Hey Manodeep - can you put a link to your slides here please?

**Comment by manodeep** [comment]
@ericbastholm That's the case frequently. I have also seen postdocs fret about writing the code and running the simulations and analysis but never really writing the (first-author) papers that are required for career progression. I think this is mostly because software has  become a critical tool across most research fields in the past 15-20 years but academia is only getting around to adapting in the past 5 years. Slowly but surely :) 

@rowlandm Slides
[RSE-Meetup-PerthDSW-May2018-with-RSE-Intro.pdf](https://github.com/rse-aunz/rse-au/files/2032788/RSE-Meetup-PerthDSW-May2018-with-RSE-Intro.pdf)

@rowlandm But we should probably have an index with all the talks/presentations/notes that we have

**Comment by rowlandm** [comment]
Just followed up with this email to the people who signed up:

Hi there,

Thanks for signing up for the Perth Face to Face meeting of Research Software Engineers on the 18th of May. It was a great meeting and your feedback and enthusiasm was appreciated!

I have sent this invite to the RSE Google Group so that you can be aware of what is going on. 

You can also check out some of what is going on via this github where we use the issues like a forum:
https://github.com/rse-aunz/rse-au

For example, you can see what I have documented around the Perth session here:
https://github.com/rse-aunz/rse-au/issues/11

Recently we put together two submissions for the eResearch Australasia 2018 conference around this community.  You might want to have a look at the abstracts to get a feel for what we are trying to do.

Pre conference workshop:
https://docs.google.com/document/d/1xQyBUS-nQbwIUnt5bGas28Y-DNCZzUWHgKIJOQweLFY/edit

Please let me know if you have any comments or questions.

Rowland Mosbergen
