### ISSUE TITLE
Are software papers the solution for measuring RSE productivity?

### ISSUE THREAD

**Issue by manodeep** [rse-aunz/rse-au#35]

**Comment by mingfangwu** [comment]
Notes I took from the Vic f2f meeting:

- There is a spectrum of software, software papers shouldn't be the only solution
- Some software is useful tool but not that innovative, should software as such be published?
- Activity traffic is an indication of software contribution/productivity, github may be the solution.

**Comment by goldingn** [comment]
photos of flipchart from the Vic meetup:
![2018_08_14 16_57 office lens 1](https://user-images.githubusercontent.com/4450731/46396119-cf4c2900-c731-11e8-96c6-e4508b5fa214.jpg)
![2018_08_14 16_57 office lens 2](https://user-images.githubusercontent.com/4450731/46396121-d115ec80-c731-11e8-9192-2e65e7aba30f.jpg)

**Comment by atruskie** [comment]
Attached are two workshop answers to this question from the QLD F2F (#19):

![img_20181008_094324](https://user-images.githubusercontent.com/1452968/46589072-14cd7500-cae9-11e8-94bc-93ec0ebf1f97.jpg)

- overall: **NO**
- are the solution to what? recognition of contribution or attribution of contribution?
- having artefacts to track is useful
- but RSE publications (even for software papers) are not related to the actual work an RSE does
- from an HR perspective, there's no point producing software papers unless it can be counted as part of your job performance
- from an academic perspective, software papers could make us look like "pretend academics"
- Academic publishing is broken anyway, why do we want to conform to that model?
- One positive of software papers is that they require software to have documentation, to be maintainable, to have a DOI, and to have the software published --- these are all good things for open and reproducible science

![img_20181008_094524](https://user-images.githubusercontent.com/1452968/46589073-19922900-cae9-11e8-8fc2-c4220198c4df.jpg)

- it encourages open source software - d/c, contribution measures
- The JOSS was mentioned
- Perhaps consulting models were a better fit than software papers?
- Again the spectrum between academic and professional has relevance
- Generally though, Yes, they are useful, gives us more KPIs

**Comment by davidbenncsiro** [comment]
One bullet point above is:
• but RSE publications (even for software papers) are not related to the actual work an RSE does

Would it be useful to solicit examples of software related publications in order to assess the relevance of such artefacts to the work of a RSE? In some cases, the publication of the software itself and related papers or conference talks or posters may be highly relevant.

Also, rather than publications, perhaps revision control repositories containing non-trivial (by some definition of non-trivial) contents may be a more useful metric of productivity than publications, since the absence of a DOI is not necessarily an indicator of the utility of software.

**Comment by GerryRyder** [comment]
Blog post by Stephan Druskat, Daniel S. Katz, David Klein et al

"[Credit and recognition for research software: Current state of practice and outlook](http://urssi.us/blog/2018/12/03/credit-and-recognition-for-research-software-current-state-of-practice-and-outlook/)"
