### ISSUE TITLE
Website, logos and branding

### ISSUE THREAD

**Issue by manodeep** [rse-aunz/rse-au#5]
We should start to put together a website for the RSE-AU. I think the RSE UK is putting together an international RSE page (http://researchsoftware.org/)

Alys Brett said that we should formally get in touch with Simon Hettrick of SSI for logos and branding for our page but should be straight-forward.

**Comment by manodeep** [comment]
Currently unadvertised but the international website is being developed here: https://github.com/RSE-leaders/researchsoftware.org/

**Comment by GerryRyder** [comment]
We still have [this page](http://www.ands.org.au/partners-and-communities/ands-communities/research-software-engineers-community-group) on the ANDS website which needs updating. Any volunteers?   Once the new RSE-AU website is up, we could link from the existing page to the new RSE-AU page which would be the main website for the community.

**Comment by nrmay** [comment]
From the feedback and discussion at the steering committee meeting, it's clear that there is an issue with our target audience not identifying with the role 'Research Software Engineer'. Therefore, I suggest that we might like to make a subtle change to our branding.
Use the name  '**Research Software Engineering Association - Australia**'.
This focus on the domain rather than the role should attract anyone who has an interest in the area and  not put off our target audience because they don't identify with a specific role. Then the marketing can revolve around the benefits of collaboration and community to various audiences.

**Comment by rowlandm** [comment]
Hi Nick,

I agree that we should be very aware about our branding. 

As per my comments in the meeting, I was using the title of the BoF and the Pre-conference workshop to test out ideas around what might stick.

At that moment what ended up being used was: 
BoF for RSEs: Recognition and Career Development for Researchers who Code

The reason I used the Recognition and Career Development (thanks to Jens for making it more positive) was to highlight the two main issues from the initial survey, and also because the Perth F2F highlighted those two as the main issues as well (if I remember correctly).

In my opinion, we need to continually test this with our audience and we also need to highlight the problem we are trying to solve in a way that is visible and clear straight away to potential community members. Think of the marketing strategy "WIIFM - What's in it for me".

I don't think we can only rely on the words "software engineering" or a variant of that. I think that currently it makes our titles longer than they should be. But I think we may have to accept that until we get more visibility within the community and build the brand of the term "RSE". It may mean that we exclude other "[Third Spacers](https://www.theguardian.com/higher-education-network/2017/sep/29/work-academic-professional-hybrid-role-say-goodbye-career-progression)"

**Comment by rowlandm** [comment]
Hi everyone,

The new website using jekyll is here, in alpha:
https://rse-aunz.github.io/

Please have a look and make suggestions.

Happy to have a session next month going through it.

**Comment by rowlandm** [comment]
Actual repo is here:
https://github.com/rse-aunz/rse-aunz.github.io

My documentation that turned into a rant on Jekyll:
https://docs.google.com/document/d/1yd6q7Tobyyl0Bo1QgtoxJkOJPwcx-PZfflISN4xIwfE/edit#heading=h.ingn54b5qo3r

**Comment by nrmay** [comment]
What about "Recognition and Career Development for Coding in Research"

1. Will attract anyone who codes.
2. Won't exlude professionals.
3. Focuses on the role, not the tile.

**Comment by kerriwait** [comment]
I'd start with a post advertising that we'll

a) be at eResearch 18 in some capacity, although exactly what that is remains to be seen at this stage
b) be organising more face to face events

**Comment by rowlandm** [comment]
Updated website to change the initial post to something more palatable.

**Comment by atruskie** [comment]
@rowlandm sorry I've been absent - most recently been sick.

I too have experienced frustration with Jekyll. A small suggestion: I've been using hugo (https://gohugo.io/) over Jekyll. It's very fast, cross-platform, and has no dependencies (requires no fancy install/c compilation/ruby framework).

**Comment by rowlandm** [comment]
Ta @atruskie  - I'm a bit committed to Jekyll now :/

Does hugo work with github ie the rse-aunz.github.io thingy?

**Comment by atruskie** [comment]
Yeah fair enough 🙂

https://gohugo.io/hosting-and-deployment/hosting-on-github/

**Comment by rowlandm** [comment]
Cheers - great to know for the future!
