### ISSUE TITLE
Deliverables for 2019 (Draft)

### ISSUE THREAD

**Issue by nrmay** [rse-aunz/rse-au#51]
1. An agreed name.
1. A manifesto.
1. An elected steering committee.
1. Seed funding.
1. A community manager.
1. A permanent online presense.
1. A schedule of events.  
    1. a Tech Talk (Feb).
    1.  a workshop at C3DIS (May).
    1. representation at ARDC skills symposium (July - provisional).
    1.  a full-day workshop at eResAU (October).

**Comment by nrmay** [comment]
An additional suggestion was to include the following item. However, this may be a stretch, given that the eResearch community as a whole is still struggling with this.

- Information Package for universities, including:
   -  Position descriptions
   -  Career path example plans
   -  Funding models from different institutions
   -  Local community engagement activity models guidlines and examples

**Comment by nrmay** [comment]
- Expanding into Asia, via Singapore and India.

**Comment by GerryRyder** [comment]
Updated deliverables for 2019 following the meeting held 17 January 2019

1. A mission statement or manifesto.
2. Profiles, personal stories. or personas of the people that form the RSE community.
3. Impact stories, for organizations.
4. A permanent web presence - to be launched at eResearch Australasia 2019.
5. Grow contacts and run face to face meetings in states and regional areas not yet engaged, such as: NSW, SA, TAS, NZ, etc.
6. An info pack for Local RSE Groups.

**Comment by GerryRyder** [comment]
It looks like the 'schedule of events' been dropped from the updated deliverables?  

It would be good to have some sort of follow up event at eRA 2019.  Perhaps a BoF or a paper rather than a workshop?  That would provide a vehicle to launch the new web presence, socialise the manifesto, share achievements to date and get input (and hopefully support!) for activities in 2020.

Also, the ARDC is looking at running some public webinars during 2019 with international presenters from the software space.  We're thinking along the lines of people like [Radovan Bast ](https://bast.fr/)and [Dan Katz](http://danielskatz.org/index.php) but nothing confirmed as yet.  We could promote these webinars through RSE-AUNZ networks (as well as the usual ARDC networks) and include a short plug for RSE-AUNZ as part of the webinar.   Something to think about anyway.

**Comment by GerryRyder** [comment]
Which reminds me, some in this group might be interested in a webinar the ARDC is running next Tuesday featuring Chris Erdmann from the California Digital Library
 
_The Carpentries: Teaching data science skills to researchers and people working in library and information-related roles_  More info and registration [here](https://register.gotowebinar.com/register/6103113463802583298)

**Comment by rowlandm** [comment]
Hi Gerry - yes, we should add the schedule back in.

**Comment by rowlandm** [comment]
[RSE-AUNZ_Deliverables_2019_v1.0.pdf](https://github.com/rse-aunz/rse-au/files/2878065/RSE-AUNZ_Deliverables_2019_v1.0.pdf)

Nick's deliverables from the Tech Talk in February.

**Comment by manodeep** [comment]
Getting workshop funding from the Academy of Sciences..
